site_name: AKTools's Documentation
nav:
    - AKTools 介绍: index.md
    - AKTools 文档: aktools.md
theme:
    name: mkdocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    locale: zh_CN
