site_name: AKTools's Documentation
nav:
    - AKTools 介绍: index.md
    - AKTools 安装: aktools.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    locale: zh_CN
