site_name: AKTools's Documentation
nav:
    - Home: index.md
    - Documentation: aktools.md
theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - python
    locale: zh_CN
